version: "3.8"

services:
  gs_nginx:
    container_name: gs_nginx
    image: nginx:stable-alpine
    volumes:
      - ./:/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "3200:3200"
      - "3300:3300"
    depends_on:
      - gs_php_fpm
    restart: unless-stopped

  gs_php_fpm:
    user: 1000:1000
    container_name: gs_php_fpm
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - gs_mysql

  gs_php_cli:
    user: 1000:1000
    container_name: gs_php_cli
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    volumes:
      - ./:/app
    depends_on:
      - gs_mysql

  gs_mysql:
    container_name: gs_mysql
    image: bitnami/mysql:latest
    environment:
      MYSQL_DATABASE: "db"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3307:3306"
    volumes:
      - gs_mysql-db-data:/var/lib/mysql/
      - ./docker/mysql/data/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: always

  gs_queue:
    user: 1000:1000
    container_name: gs_queue
    build:
      context: .
      dockerfile: docker/php-cli/Dockerfile
    command: php /app/src/yii queue/listen --verbose=1 --color=1 --channel=main
    tty: true
    volumes:
      - ./:/app
    depends_on:
      - gs_mysql

  gs_redis:
    container_name: gs_redis
    image: redis:6-alpine
    volumes:
      - gs_redis_data:/data
    ports:
      - "6379:6379"
    restart: unless-stopped

networks:
  default:
    external: true
    name: gs_network

volumes:
  gs_mysql-db-data:
  gs_redis_data:
